### ISSUE TITLE
can't compile with 2.1.5 ruby in OS X

### ISSUE THREAD

**Issue by turbod** [denofevil/debase#17]
Hi,
I can't compile debase gem. This is the log:

````shell
cat /Users/username/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-14/2.1.0-static/debase-0.1.0/gem_make.out
/Users/norbi/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20141201-2519-da10ov.rb extconf.rb
checking for vm_core.h... no
checking for vm_core.h... no
checking for vm_core.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling breakpoint.c
compiling context.c
compiling debase_internals.c
In file included from /Users/norbi/.rvm/gems/ruby-2.1.5/gems/debase-ruby_core_source-0.7.2/lib/debase/ruby_core_source/ruby-2.1.5-p273/method.h:14,
                 from /Users/norbi/.rvm/gems/ruby-2.1.5/gems/debase-ruby_core_source-0.7.2/lib/debase/ruby_core_source/ruby-2.1.5-p273/vm_core.h:24,
                 from ./hacks.h:1,
                 from debase_internals.c:2:
/Users/norbi/.rvm/gems/ruby-2.1.5/gems/debase-ruby_core_source-0.7.2/lib/debase/ruby_core_source/ruby-2.1.5-p273/internal.h:209: error: expected ';', ',' or ')' before 'x'
make: *** [debase_internals.o] Error 1

make failed, exit code 2
````

**Comment by os97673** [comment]
it may be fixed with #18, let me know if it is not

**Comment by turbod** [comment]
It's works. Thx.
